-   id: cocogitto
    name: cocogitto
    description: 'lint commit messsages with cocogitto'
    entry: cog verify
    language: rust
    types: [text]
    stages: [commit-msg]
    args: []
    require_serial: false
    additional_dependencies: ["cli:cocogitto:6.2.0"]
    minimum_pre_commit_version: '0'
