-   id: cocogitto
    name: cocogitto
    description: 'lint commit messsages with cocogitto'
    entry: cog verify
    language: rust
    types: [file]
    stages: [commit-msg]
    args: [--file]
    require_serial: false
    additional_dependencies: ["cli:cocogitto:6.2.0"]
    minimum_pre_commit_version: '0'

-   id: cocogitto-branch
    name: cocogitto-branch
    description: 'protect remote branch prior push'
    entry: cog check
    language: rust
    types: [text]
    stages: [pre-push]
    args: [HEAD..origin/HEAD]
    pass_filenames: false
    require_serial: false
    additional_dependencies: ["cli:cocogitto:6.2.0"]
    minimum_pre_commit_version: '0'
